---
blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions and Answers about V
    url: https://github.com/vlang/v/discussions/categories/questions-and-answers
    about: Please ask and answer questions as a discussion thread
  - name: 💬 Discord Server
    url: https://discord.gg/vlang
    about: You can join our Discord server for real time discussion and support
