name: C2V apps

on:
  push:
    paths-ignore:
      - "**.md"
      - "doc/**"
      - "examples/**"
      - "tutorials/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "doc/**"
      - "examples/**"
      - "tutorials/**"

concurrency:
  group: build-c2v-apps-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  doom-compiles:
    runs-on: ubuntu-20.04
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Build V
        run: make && ./v symlink -githubci

      - name: Build C2V
        run: |
          echo "Clone C2V"
          mkdir -p ~/code/
          git clone --depth 1 https://github.com/vlang/c2v ~/code/c2v
          ln -s ~/code/c2v ~/.vmodules/c2v
          v -g ~/.vmodules/c2v/
          ~/.vmodules/c2v/c2v || true

      - name: Install Doom Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libpng-dev libsamplerate0-dev

      - name: Build original Chocolate Doom
        run: |
          git clone --quiet --depth 1 https://github.com/vlang/doom ~/code/doom
          cd ~/code/doom/chocolate-doom
          cmake -DCMAKE_BUILD_TYPE=Debug .
          make chocolate-doom

      - name: Translate the whole game in project/folder mode and compile it
        run: |
          cd ~/code/doom
          touch ~/DOOM1.WAD
          WAD_FILE=~/DOOM1.WAD ~/code/doom/build_whole_project.sh
