name: hub_docker_ci

on:
  workflow_dispatch:

jobs:
  publish-new-docker-images:
    strategy:
      matrix:
        os: [debian, alpine]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'vlang/docker'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to hub.docker.com
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: generate tags conditionally
        id: gen_tags
        run: |
          if [[ ${{ matrix.os }} == 'debian' ]]; then
            echo 'TAGS=thevlang/vlang:latest,thevlang/vlang:${{ matrix.os }}' >> $GITHUB_OUTPUT
          else
            echo 'TAGS=thevlang/vlang:${{ matrix.os }}' >> $GITHUB_OUTPUT
          fi

      - uses: docker/build-push-action@v4
        name: Build and deploy v image
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.gen_tags.outputs.TAGS }}
          file: docker/vlang/Dockerfile.${{ matrix.os }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: 'USER=thevlang'

      - uses: docker/build-push-action@v4
        name: Build and deploy developer build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: thevlang/vlang:${{ matrix.os }}-dev
          file: docker/vlang/Dockerfile.${{ matrix.os }}.dev-full
          build-args: 'USER=thevlang'
          push: ${{ github.event_name != 'pull_request' }}
