name: toml CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  toml-module-pass-external-test-suites:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      TOML_TESTS_PATH: vlib/toml/tests/testdata/burntsushi/toml-test
      TOML_TESTS_PINNED_COMMIT: 8baf830
    steps:

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y jq
      - name: Build V
        run: make -j2 && ./v -cc gcc -o v cmd/v

      - name: Run local TOML tests
        run: ./v test vlib/toml

      - name: Clone BurntSushi/toml-test
        run: |
          git clone https://github.com/BurntSushi/toml-test.git $TOML_TESTS_PATH
          ## TODO: update/remove this pinning once all our skip lists are empty:
          git -C $TOML_TESTS_PATH checkout $TOML_TESTS_PINNED_COMMIT

      - name: Run BurntSushi TOML tests
        run: ./v vlib/toml/tests/burntsushi.toml-test_test.v
